language: python
python: 3.6

services:
 - postgresql

install: 
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter
before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
script: 
 - pytest --cov-report term-missing --cov=app

after_success:
 - coveralls
 - codeclimate-test-reporter